### ISSUE TITLE
Use Socket.IO-Client to connect channels

### ISSUE THREAD

**Issue by shitone** [django/channels#1038]
Hi, I want o use the client js of socket.io to emit message to channels.  I use the interface socket.emit(eventName[, ...args][, ack]) of socket.io like this in my js file:
`socket.emit('my_event_str', {data: 1}); `
However, I don't know how to accept the eventName in my django-channels. According to  Docs of django-channels, I set my routing like this:
```
 websocket_urlpatterns = [
    path('ws/chan', ws.MyConsumer),
]
```
But how could I set or handle  the `my_event_str`  in order to recieve the data.

**Comment by andrewgodwin** [comment]
Channels doesn't support socket.io - it's a different protocol that isn't websockets or HTTP but layers on top of them. You'll have to use a socket.io server if you want to use it.

**Comment by devprofile98** [comment]
can we use Qt websocket for connecting to channels?
after i try this channe says:
WebSocket HANDSHAKING /ws/adminSupport/ [127.0.0.1:48118]
WebSocket CONNECT /ws/adminSupport/ [127.0.0.1:48118]
Exception inside application: Expecting value: line 1 column 1 (char 0)
  File "/home/sub/.local/lib/python3.7/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/sub/.local/lib/python3.7/site-packages/channels/utils.py", line 52, in await_many_dispatch
    await dispatch(result)
  File "/home/sub/.local/lib/python3.7/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/sub/.local/lib/python3.7/site-packages/channels/generic/websocket.py", line 196, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/home/sub/Documents/django/portfolio/portfolio/consumer.py", line 62, in receive
    jsonR = json.loads(text_data)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
  Expecting value: line 1 column 1 (char 0)
WebSocket DISCONNECT /ws/adminSupport/ [127.0.0.1:48118]

**is it  because of channels ?
or my Qt client?**

**Comment by carltongibson** [comment]
```
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

I'd guess your client is sending malformed messages. You'll need to investigate.

**Comment by devprofile98** [comment]
thank you

**Comment by goharattiq** [comment]
@andrewgodwin still we do not have channels and sockets.io compatibility ??

**Comment by carltongibson** [comment]
@goharattiq See Andrew's original reply. Nothing has changed. It's not likely to.
