### ISSUE TITLE
Sessions data corrupted

### ISSUE THREAD

**Issue by DiegoGallegos4** [django/channels#1047]
- Ubuntu 16.04
- Channels 2.1.1, Django 2.0.4
- Served background tasks via daphne, with nginx as a web server

Traceback: 

> May 15 20:30:52 ip-172-21-33-32 daphne[9222]: WARNING 2018-05-15 20:30:52,086 Session data corrupted
May 15 20:30:52 ip-172-21-33-32 daphne[9222]: DEBUG 2018-05-15 20:30:52,088 HTTP 403 response started for ['127.0.0.1', 48324]
May 15 20:30:52 ip-172-21-33-32 daphne[9222]: DEBUG 2018-05-15 20:30:52,089 HTTP close for ['127.0.0.1', 48324]
May 15 20:30:52 ip-172-21-33-32 daphne[9222]: DEBUG 2018-05-15 20:30:52,090 HTTP response complete for ['127.0.0.1', 48324]

Sessions served by uwsgi are correctly being served. 

This is how is served by nginx: 

```
server {
    listen 443;
    ssl on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Disable SSLv3 (CVE-2014-3566)

    # Disable emitting nginx version in error messages and in the "Server"
    # response header field.
    server_tokens off;

    ssl_certificate       project.crt;
    ssl_certificate_key    project.key;
    ssl_client_certificate project.ca;
    ssl_verify_client      optional;

    # Set the maximum allowed size of the client request body, specified in the
    # "Content-Length" request header field.
    client_max_body_size 20M;

    # These requests are handled by daphne
    location /stream {
        # daphne server running on port 8001 so we set a proxy to that url
        proxy_pass http://0.0.0.0:8001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect   off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }

    # These requests are handled by uwsgi
    location / {
        include uwsgi_params;
        uwsgi_pass unix:/run/uwsgi/app/project/socket;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Make the following two variables accessible to the application:
        uwsgi_param SSL_CLIENT_VERIFY $ssl_client_verify;
        uwsgi_param SSL_CLIENT_RAW_CERT $ssl_client_raw_cert;
    }
}
```

**Comment by andrewgodwin** [comment]
Hmm, often this is a problem with the Django session framework, triggered by changing your `SECRET_KEY` value. Are the settings between the two runtimes completely the same?

**Comment by DiegoGallegos4** [comment]
Yes they are the same settings. All being taken from the configuration file.

**Comment by andrewgodwin** [comment]
Can you try clearing your session store between changeovers and see if it continues to happen?

**Comment by DiegoGallegos4** [comment]
Is this equivalent to flushing the django_sessions table? Because I have already tried that.

**Comment by andrewgodwin** [comment]
Yes, that is what I meant. If that's not doing it then I'm afraid I don't know what the cause is - I won't be able to solve this until I know what triggers it (sessions work fine for most people).

Do sessions work if you uninstall channels? If you use gunicorn rather than daphne or wsgi? Do they fail on all URLs or just one? Basically, you need to get to the point where they work again, work out what got you there, and let me know so I know what to trace down further.

**Comment by dlernstrom** [comment]
@andrewgodwin 
I was also running into the same issue where I could trigger a "Session data corrupted".  It seems I just stumbled upon my issue, though.  Originally, I was running:
channels==2.1.1
channels_redis==2.1.0
Updating channels_redis to 2.2.1 resolved the problem.

With the old version, we could trigger the issue fairly easily with the following lines of code (from another part of the Django app):
```
channel_layer = get_channel_layer()
async_to_sync(channel_layer.send)('our_chatroom', {'type': 'chat_message', 'text': 'test page loaded'})
```
and then hammering the refresh button on that page in a web browser.

**Comment by andrewgodwin** [comment]
Hmm. Well if that fixed it, I am more inclined to close this for not being reproduceable :)

**Comment by DiegoGallegos4** [comment]
I ended migrating the project to use container and it worked. My channels_redis version is 2.1.1 so I don't think that's the issue. It maybe a very subtle bug.

**Comment by andrewgodwin** [comment]
OK, I'm going to close this for now then. If someone can reproduce it on the newest version, please reopen with details!

**Comment by dlernstrom** [comment]
Just as a follow up, in case anybody ever reads through this thread and discovers the `Session Data Corrupted` issue that I was being faced with, I'll add an update to what we were faced with.
As I mentioned above, allowing Daphne to serve the traditional request/response stuff and disabling Gunicorn did completely resolve my `Session Data Corrupted` errors.

As it turns out, the error that I've been plagued with now has to do with the combination of the `websocket` timeout as well as the `group_expiry` (24 hours, https://github.com/django/channels/issues/999).  In my infrastructure, I have a fleet of RPi devices that connect in to Daphne/Channels over a web socket so that the server can push out information.  These devices create a custom channel unique to the deployment scenario of the device. What I'm discovering is that Channels expires the group and the RPi device doesn't find out the group was destroyed because the web socket session is still active.  I realize that my issue now diverges from the topic of this thread, so I'm going to find a different venue to pose the question of how to get the group_expiry to play nicely - probably Stack Overflow.  Cheers!
