### ISSUE TITLE
Add overridable disconnect method to AsyncHttpConsumer

### ISSUE THREAD

**Issue by erm** [django/channels#1051]
Long-polling HTTP requests using `AsyncHttpConsumer` are unable to detect disconnect messages from the application queue without overriding the `__call__` method on the consumer class. An overridable `disconnect()` method that is called when receiving `http.disconnect` messages would allow `AsyncHttpConsumer` implementations to define the consumer disconnect behavior (cleaning up tasks, handling streams, gracefully closing the consumer, etc.).

Refers to discussions in https://github.com/django/channels/issues/1049

**Comment by andrewgodwin** [comment]
Implemented this, and additionally made `disconnect` trigger even on error states as its job is cleanup.

**Comment by erm** [comment]
Thanks!

**Comment by jkarneges** [comment]
Hi, I'm not sure but I think the `return` after `await self.handle()` needs to be removed? Otherwise, if handle() spawns a streaming task and returns, then the loop exits and disconnect is called immediately. And if handle() doesn't spawn a task and return, then the receive loop will never run and disconnects won't be detected.

**Comment by andrewgodwin** [comment]
@jkarneges Yes, I think you're right - I've removed it.
