### ISSUE TITLE
[2.1.1] Workers and BackgroudTasks dont work with InMemoryChannelLayer

### ISSUE THREAD

**Issue by creativequality** [django/channels#1060]
We have a project that uses channels 1.x to implements websockets and async task. I develop in Windows. For now we use "runserver" and "in memory channel".

We're migrating our project from Channels 1.x to 2.x.

The websockets stuff is migrated and working.

In channels 1.x we have a "Channel('channelname').send()" (An async task throwed from a django view) that works like a charm. I migrate to Channels 2.x with the help of "Worker and Background Tasks" section of doc. When I test, nothing happens. I search forums, blogs, issues, docs and do a lot of tests (with runserver and runworker). Finally I decide clean my tests and return to first migrating steps to testit with Redis. I install Redis (using Windows linux subsystem, because to use Redis in Windows I have to compile) and test it, and magycally my original simple code (from docs section) works using runworker (not with runserver as in channels 1.x)

So as the title says, Workers and BackgroudTasks dont work with InMemoryChannelLayer. I dont want Redis for now, so its important thing. 
Another related question: As I say, I have to throw runworker apart from runserver (channels 1.x run both). Is possible to integrate this "worker" or "thread" to "runserver" as in Channels 1.x? Its more easy and quickly only throw one cmd and one command

Thank you very much.

**Comment by andrewgodwin** [comment]
The in memory layer only works within a single process - it can never go between separate processes, and so can't get to workers. If you want inter-process communication you have to use a networked layer like the Redis one.

It's also not possible to integrate the worker into the server now because they're quite different. The worker is only needed for background tasks, not requests.
