### ISSUE TITLE
Exception inside application: Reader at end of file

### ISSUE THREAD

**Issue by ixser** [django/channels#1199]
When I runserver on my project, I always saw this traceback, it seemes that it was calsed by redis connection,?  it works right while i build an connection, but when i build annother, this problem raising, how can i use it properly

**Comment by andrewgodwin** [comment]
I don't know what's causing it but it's not a bug in Channels - you should make sure your Redis server and packages are all up to date. A few other people have had the same issue and it often turned out to be a problem with either their Redis configuration or they were running a very old version of a package.

**Comment by keomabrun** [comment]
I have the same problem running with Redis 5.0.6 on Heroku. @jeeyshe did you solve you issue ?

Other python3 packages version I use:
- `redis` v3.4.1
- `django-redis` v4.11.0

**Comment by jeeyshe** [comment]
Would  u  give a shortscreen ?  It is a year ago ， I  dont  remember the detail,  I  am sure having soveld  it,  wait me look for the problem  in my code
