### ISSUE TITLE
how to close current connection if no message sended from client after a few minutes

### ISSUE THREAD

**Issue by fenghaoyu** [django/channels#1444]
Sorry to ask here.
I'm trying to find a solution to solve this by reading the documents, but no help.
English is not my mother tongue, so may be there is a solution but i can't find.
Also, i can't connect to stackoverflow.

Here is my question:
Is there is a way to do this?
If no message sended from client after a few minutes, like two or three minutes, i want to close it and discard it from group.
Any suggestion or question will be thankful!

**Comment by hishnash** [comment]
the simple solution is to close every connection after a given timeout:  `--websocket_timeout` command-line option will do this.

However if you want to only do this after `inactivity` then you need to setup a middleware that forwards messages on to the child and handles this timeout.

This is not a trivial middleware to write (due to the need to use nested async tasks). Might be better to ask this question over on stack overflow so we can keep this area for bugs: https://stackoverflow.com/questions/tagged/django-channels

**Comment by fenghaoyu** [comment]
thank you very much for helping.








------------------ Original ------------------
