### ISSUE TITLE
Reloading changes after deployment with uvicorn without disconnecting connected websockets

### ISSUE THREAD

**Issue by Ammadkhalid** [django/channels#1460]
Hi,

one question:

I wanted to send `HUP` signal to uvicorn for reloading my deployed changes. But i don't want current ws to disconnected. I tried sending `HUP` signal, ```kill -HUP $(pgrep uvicorn)```.  And it disconnect my ws as expected. I don't think if there is way to do this without disconnecting connected websocket connections? or i have to implement auto reconnect ws connections from client side?

**Comment by carltongibson** [comment]
Nice question. 

>  And it disconnect my ws as expected. I don't think if there is way to do this without disconnecting connected websocket connections? 

I **don't think** you're going to be able to do that. (You'd have to put an application to maintain the websocket in between your frontend server and the app you're restarting. 

> or i have to implement auto reconnect ws connections from client side?

I think this is the way. You should probably do this anyway, since connections drop for any number of reasons. 

HTH
