### ISSUE TITLE
group_send does not work for a model instance

### ISSUE THREAD

**Issue by nebiyuelias1** [django/channels#1594]
I am trying to use group_send using a model instance:
```
def group_send(moogt, notification):
    channel_layer = get_channel_layer()
    if moogt:
        async_to_sync(channel_layer.group_send)(f'{moogt.id}', notification)
```
Here notification, contains a model object like this:
```
notification = {
        'type': 'receive_group_message',
        'argument': argument,
        'event_type': message_type
    }
```
Of course, I do serialize the model object in the consumer, inside **receive_group_message**. But I am not getting anything in my websocket clients.

**Comment by pawel-czarnecki** [comment]
Actually I've encountered the same problem, my group doesn't received anything back while using group_send from channel_layer. I haven't seen any changes in docs about this topic.

**Comment by pawel26** [comment]
@nebiyuelias1 which version of channels are you using?

**Comment by nebiyuelias1** [comment]
channels==2.4.0

**Comment by sevdog** [comment]
`group_send` behaviour dependes on channel layer.

If you use `InMemoryChannelLayer` it is fine to leave model instances into messages. but if you use `RedisChannelLayer` (or any other channel layer which needs to interact with an _external_ system) this is not possible anymore since message data needs to be **serialized** in the process. By default django model instances are not serializable by common used serializers (json/msgpack).

> Of course, I do serialize the model object in the consumer, inside **receive_group_message**.

You also need to serialize the model in your **group_send** _before_ passing to channel layer.

However I would expect some errors to be thrown  like "unable to serialize instance of <model>", if you do not see any I suppose that the serializer you ara using is failing _silently_.

**Comment by carltongibson** [comment]
What @sevdog says is correct. 

I don't think there's enough to really go on as a concrete issue.
