### ISSUE TITLE
enforce_ordering message dropping should close a WebSocket

### ISSUE THREAD

**Issue by trainman419** [django/channels#195]
If I use `enforce_ordering` and I send messages over a websocket more quickly than my consumer can process them, eventually the `__wait__` channel becomes full and starts dropping messages.

Since `enforce_ordering` expects messages with sequential IDs, if a message gets dropped it causes the enforce_ordering filter to wait forever for that message.

The stack trace that I get when this happens is:

```
2016-06-03 18:25:37,917 - ERROR - worker - Error processing message with consumer model.consumers.ws_receive:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/channels/worker.py", line 106, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/channels/sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/channels/sessions.py", line 127, in inner
    "full __wait__ channel for socket %s" % message.reply_channel.name
ChannelFull: Cannot add unordered message to already full __wait__ channel for socket websocket.send!XzbYSOku
```

**Comment by andrewgodwin** [comment]
Hmm, this is going to happen - with enforce_ordering on we have to drop whole sockets if you get lagged behind - but it should just do that (disconnect the socket) rather than tracebacking.

**Comment by trainman419** [comment]
I'm willing to try to put together a simple test case that reproduces this, but I'm new to django and channels and I'm not sure which tools to use. Is there any documentation on the subject that you can point me to?

**Comment by andrewgodwin** [comment]
There's not a lot about writing tests against Channels itself; you'd have to take a look at the existing test suite if you're interested, and I'm not sure that has the example of setting a low channel capacity and testing channel decorators combined.

**Comment by andrewgodwin** [comment]
Renamed this to better describe what it is, which is that we need to have a way to close WebSockets when their messages get dropped due to ordering violations, but not have the channels code specifically looking out for websockets.

My current suggestion would be that if a message is dropped by ordering (or something else) and channels knows it's definitely gone, a standardised "control" message reply is sent back to the `reply_channel` if one is present saying that it was dropped.

We'd need to make the worker do this, specify what the control message looks like in the asgi spec, and then have Daphne respect that message and close websockets.

**Comment by asgorh** [comment]
Is there any chance that this issue will be fixed in near future?

Regards
Tom

**Comment by andrewgodwin** [comment]
Hopefully - the new WebsocketCloseException pattern that came in with 1.0.2 certainly gives us a route to better handle this.

**Comment by asgorh** [comment]
Yeah, I saw this feature and thought about its impact on this issue resolving. Fingers crossed then!

Regards
Tom

**Comment by sachinrekhi** [comment]
@andrewgodwin I'm running into this same issue currently in production. What's strange is that after the ChannelFull exception is raised, I see a spike in CPU usage and the workers get extremely busy even though there is very little load on the server. I also see a huge jump in requests per second to the Redis layer. When I restart just the channel workers, everything goes back to normal: CPU usage, worker load, and Redis requests and now the busyness of the servers seems to fall back down to match the actual user load.

It feels like after the ChannelFull exception is raised, maybe it's somehow constantly retrying to push the request back on the channel? I do get 100s of these errors in quick succession whenever this happens, but I can't be sure whether it's the message being retried to push back on the channel or whether the client is just sending lots of messages.

If I'm understanding your suggested fix, then what we'd do is instead of having the enforce_ordering decorator rethrow the ChannelFull error when it encounters it, it will instead throw the WebsocketCloseException, which will cause the worker processing the message to simply close the web socket connection. It seems since you've already built out support for the WebsocketCloseException, that's all that needs to be done, correct?

**Comment by proofit404** [comment]
@sachinrekhi Hi 

To understand your issue we need some additional info. Can you provide `hunter` tracing tool output as a gist? One second from the ChannelFull exception moment should be enought.

Something like this should work

```
PYTHONHUNTER="module__regex='channels.*', threading_support=True, actions=[CallPrinter]" <runworker command>
```

Regards, Artem.

**Comment by sachinrekhi** [comment]
@proofit404 I'm unfamiliar with hunter, but based on the docs, it's sounds like I do the following, correct?

1. Install hunter package into my virtual env
2. Run my workers in production with this command instead of my typical command, which will automatically activate the hunter output:
```
PYTHONHUNTER="module__regex='channels.*', threading_support=True, actions=[CallPrinter]" <runworker command>
```
3. The hunter output will be sent to wherever I have stdout sent? (currently using supervisord which redirects stdout to a file)
4. Once I encounter the error again, then I should be able to go back to the stdout file and grab the section immediately after the ChannelFull error and share it here?

Do you know if hunter adds much latency to production?

**Comment by andrewgodwin** [comment]
@sachinrekhi Yeah, the interaction between ChannelFull and the message re-ordering is probably one of those things that would cause a tight spin loop. Just dropping the connection is, as you suggest, likely to "fix" it, though I don't have the time to build out and test that given that channels 2 needs working on (and of course doesn't have this issue since I entirely removed all aspects of the design decision that caused the need for enforce_ordering)

You can try writing your own copy of enforce_ordering and raising the appropriate exception there? You can just copy the Channels code and change it around, there's no special meta or anything to swap out, just the import to use your version.

**Comment by proofit404** [comment]
While @andrewgodwin working on Channels 2.0 I'm trying to keep things going on the current version.

@sachinrekhi Yes, hunter activation will affect production installation dramatically. But The program output will be also huge. You can try to setup one separate node working in this mode.

Yes, all you need to do is install hunter and setup `PYTHONHUNTER` variable.

**Comment by sachinrekhi** [comment]
I attempted the solution suggested above, but I think there is a bug in WebsocketCloseException. The run() method is:

```
def run(self, message):
    if message.reply_channel.name.split('.')[0] != "websocket":
        raise ValueError("You cannot raise CloseWebsocketError from a non-websocket handler.")
    message.reply_channel.send({"close": self._code or True})
```

It attempts to verify the reply channel name, but don't the reply channel's now start with **daphne**, not **websocket**?

Or should it being verifying the channel name, not the reply channel name?

**Comment by proofit404** [comment]
Yes, [it is](https://github.com/django/daphne/blob/05bd4ac258ee4d3fa1a9d2c6096df44b28810721/daphne/server.py#L85)

**Comment by proofit404** [comment]
@sachinrekhi this should be fixed with https://github.com/django/channels/commit/7333cf4e76be7aae73cb0254063810d2d5dfbcbe

**Comment by sachinrekhi** [comment]
@proofit404 great! thank you

**Comment by sachinrekhi** [comment]
One thing I noticed is that in my code I have the enforce_ordering decorator on the websocket connect, receive, and disconnect consumers. But it looks like from the docs it's only supposed to be on the receive consumer, is that correct?

**Comment by sachinrekhi** [comment]
Actually it looks like the enforce_ordering decorator is required on the connect consumer as well as the receive consumer. This is because enforce_ordering assumes the first message it sees has order=0 which happens with the connect message.

Without the decorator on connect, your first receive message is immediately put on the wait channel.

Right?

**Comment by proofit404** [comment]
Receive messages can be sent to the channel layer only after connect consumer finish it's work. Because in it we decide if we accept connection or not.

**Comment by andrewgodwin** [comment]
enforce_ordering is not _required_ on the connect function any more but as you say, it will need it to see packet 0.

**Comment by sachinrekhi** [comment]
OK, thanks guys, good to know.

One additional question, is it true that a reply channel name is unique to each and every websocket connection and is not re-used? So even if the same client closes and then opens a new websocket connection, it will get assigned a different reply channel name, correct?

Here's why I ask... While I now close the websocket connection when a wait channel is full, I'm realizing that is not enough to reduce the server load since even though the client socket is closed, the workers continue to work there way through processing the entire wait channel, even though the replies can no longer be sent to the client.

To solve this, I've now introduced a drain_wait_channel() function that I call before I raise WebsocketCloseException to close the socket. The drain_wait_channel() method is similar to requeue_messages() in that it basically receives all messages from the wait channel, but drops them instead of requeueing them anywhere.

I think this will work great as long as the reply channel name is not re-used when the client opens a new connection (or re-used by any other socket connections), so wanted to verify.

**Comment by proofit404** [comment]
Yes, reply channel names are not reused even if the same client reconnected immediately.

**Comment by andrewgodwin** [comment]
`enforce_ordering` is gone in Channels 2, so we fixed this eventually!
