### ISSUE TITLE
Data Binding Filters

### ISSUE THREAD

**Issue by Gromph** [django/channels#369]
I'm migrating a project away from using swamp dragon to django channels. Swamp dragon's self publishing models is simliar to channels data binding. One nice feature it had was to be able to set a filter when subscribing to a model so that the client only received records that matched the filter. An example might be to have a chat app with multiple rooms. All chat is stored in one table with a room field. Then each client would specify a room filter to receive only the chat for one room.

Is it possible to do something like that now with django channels?

**Comment by andrewgodwin** [comment]
Yes, you just need to implement the filtering as part of the implementation of `group_names` - rather than saying what filters apply to each client connection, you work out what set of groups to send updates into (e.g. one group per room) and then add or remove client connections from groups as needed.
