### ISSUE TITLE
ASGI - Direct mode?

### ISSUE THREAD

**Issue by tomchristie** [django/channels#413]
Hiya,

I'm looking into the ASGI spec at the moment, and have a use-case that might be worth talking through to see if there's anything of value here. Very welcome to simply close this off if you don't think it adds anything of value.

I'd like to be able to use the ASGI messaging interface, in order to allow me to have a server that supports HTTP, WebSockets and other protocols, however I'm not interested in ASGI-as-bus-layer. I don't mind that long lived connections will get torn down on redeploys, and I don't need broadcast functionality.

Rather than running under this setup:

```
Protocol Server -> Channels <- Application Worker -> Application Consumer
```

I'd instead like to simply be able to provide a protocol server with a consumer interface and pass messages directly to it (with the `reply_channel` providing the callback to the protocol server).

```
Protocol Server -> Application Consumer
```

(There's no routing going on here, but the top-level consumer might then route the message on to a protocol specfic consumer, depending on the app configuration)

In this setup I can eg. write a gunicorn worker class that uses the ASGI messaging format instead of the WSGI format, and be able to support multiple protocols in an otherwise standard setup.

It may be that I'm missing some part of the puzzle here, but from digging around this seems to meet my needs (again, aware that comes with the constraints noted above, but I'm okay with that).
- Is there anything clearly problematic that I'm missing in this setup?
- Would a "direct mode" that simply points an interface server directly at a consumer interface be a valuable direction to take for a documented deployment configuration? (aka, let's replace WSGI with a more generic messaging interface, without changing any other moving parts)

Thanks so much for the wonderful work you've been doing here! ✨

**Comment by andrewgodwin** [comment]
So, this was one of the things I was considering earlier on in the design process, and there's nothing to theoretically get in the way, but there are caveats.

First, you still need an intermediary object to act as the channel layer so it's loose coupling between components - otherwise you'd need to entirely uproot the protocol design, and I think it's a sensible decision anyway. `asgiref` already has an in-memory, threadsafe channel layer that would serve this purpose.

Secondly, you need every part of the process to be running asynchronously, so that both halves can run independently. This is not safely possible with Django as it stands unless you use standard threading, which of course massively impacts performance.

So, with those caveats, you could do entirely in process messaging, which seems to be what you want?

**Comment by tomchristie** [comment]
> First, you still need an intermediary object to act as the channel layer so it's loose coupling between components 

Gotcha. In that case presumably you *do* end up with broadcast being supported.

> Secondly, you need every part of the process to be running asynchronously

Yes, that's the plan. (Aware of some of the issues around that, such as DB bottleneck, unnoticed blocking code using existing standard libs etc.)

Thanks. Will let you know if I end up making progress here.

**Comment by andrewgodwin** [comment]
Yes, broadcast will work in-process still - you're essentially just limiting the universe that the channels code operates in to a single process memory space rather than a network segment.

**Comment by andrewgodwin** [comment]
Was there anything else on this ticket, or should I close it?
