### ISSUE TITLE
Is there any way WebsocketDemultiplexer can avoid re-serializing the data in receive?

### ISSUE THREAD

**Issue by germanjoey** [django/channels#474]
Hello,

I've started developing an app using the multiplexer/demultiplexer classes, and, upon looking into their internals to get a better idea of how data was swirling around, I noticed that incoming data goes through a flow like this:

-> WebsocketDemultiplexer.raw_receive (inherited from JsonWebsocketConsumer) deserializes the message via json.loads
-> WebsocketDemultiplexer.receivere-serializes message['payload'] via json.dumps, assigning it to message['text']
-> CustomConsumer.raw_receive (inherited from JsonWebsocketConsumer) deserializes message['text'] via json.loads
-> CustomConsumer.receive then does whatever it needs to.

This is kinda wasteful; instead, could a flag be set in WebsocketDemultiplexer.receive, such as message['_demuxed'] or whatever, so that the second JsonWebsocketConsumer.raw_receive could bypass its call to json.loads? Or would artificially modifying the message contents in flight be a bad idea for other reasons? Basically, my concern is that json serialization/deserialization is a relatively expensive operation, and since this is right in the middle of the user's request it would be good to avoid it if possible!

Thanks,
Joey

**Comment by andrewgodwin** [comment]
That's a good point - the reason this is designed like this is so that the consumer behind the multiplexer sees the same contents as one not behind a multiplexer, but I agree it's inefficient.

There's not a super easy way around this without breaking that abstraction - if we made something that people could use to be efficient, it necessarily would be something you couldn't normally do on a normal receive.

I need to have a little think about this and if it makes sense to have in the API or not :)

**Comment by jeremytiki** [comment]
What if instead of providing an encode_json and decode_json channels just provided an encode and decode function on the WebsocketsConsumer? Then channels could allow a user to pass in a callable when they inherit from WebsocketConsumer and the end user could decide how everything is encoded or decoded, and wether or not is should be. This would allow this ticket and #534 to both be fixed relatively easily.

**Comment by andrewgodwin** [comment]
Well, you could do that with the `encode_json` and `decode_json` methods right now via subclassing, I don't see a need to add extra logic to look for class body variables. What I will do is rename `encode_json` to `encode` and same for decode, so it's clear you can be a bit more generic.

**Comment by jeremytiki** [comment]
That does make more sense. Would it also be a good idea to explicitly explain this decision in the docs under the "Getting Started with Channels" section to avoid further questions?

**Comment by andrewgodwin** [comment]
Probably - I'm starting a full rewrite of the docs along with the 2.0 stuff, and I'm hoping to make this distinction clearer (we'll get a lot of docs "space" back by not having ordering or channel_session any more)

**Comment by jeremytiki** [comment]
Alright, do you want me to go ahead and make the code and doc changes so that this issue can be closed, or would you rather wait for the full rewrite?

**Comment by andrewgodwin** [comment]
Well, the actual ticket itself is about a different issue which is the multiplexer abstraction itself being wrong, and that's also going to be fixed at some point as the entire multiplexer stack is being redone as the new style consumers - so I'll close it when we get there. Don't worry about working on stuff now.

**Comment by andrewgodwin** [comment]
Multiplexing got removed from 2.0 while it's rewritten from the ground up (with a better abstraction that solves these issues), so closing this.
