### ISSUE TITLE
Django channels for asynchronous periodic tasks

### ISSUE THREAD

**Issue by yanikkoval** [django/channels#551]
I found that most of the docs regarding Django Channels are about WebSockets. But I want to use them in a different way, and I believe it is possible.

How to run the async periodic task using Django channels? For example, I want to check the temperature on some website (through the API) every 15 seconds and I need a notification when its hit > 20.

It also means that this task will live for a long time (maybe even for 3 months), is Django capable of keeping the consumers live for a long time?

Thank you.

**Comment by andrewgodwin** [comment]
Consumers are meant to never do a blocking task; it's an evented system, where rather than sections of code separated by yields or callbacks they're separated by channels.

If you want to do something periodically, there is an in-progress scheduler that will fire off a consumer based on time periods being developed in #530; alternatively, you could make a long-running management command that just sent onto a custom channel every X seconds and tie your consumer to that (but at that point, you likely can just put the logic in that management command)

**Comment by yanikkoval** [comment]
@andrewgodwin, thank you for answer
