### ISSUE TITLE
How to setting django-channels socket connect timeout?

### ISSUE THREAD

**Issue by lingliqianxun** [django/channels#563]
How to setting django-channels socket connect timeout?
I have tested that one client connet to server,then do nothing,it will be disconnet about 20~30mins.
I want to set timeout custom,how to add in django-setting for a global or writ a file to reload?

**Comment by andrewgodwin** [comment]
This is better suited for the django-users mailing list, but I will answer here as it is at least public.

Channels (in particular, Daphne) has two cases it will disconnect a client:
 - If the client stops responding to ping packets, meaning the actual underlying socket has been lost
 - If the group_expiry time is reached, which by default is 86400 seconds, or one day

Neither of these is a socket timeout or is naturally 20 - 30 minutes, so I suspect your disconnections are caused by something else (your browser? your network connection dropping? etc.)

**Comment by lingliqianxun** [comment]
Yes，that should be group_expiry time is reached.But I want to disconnect client about 10 minutes if client not send any data to server,how to setting?Writ a Heartbeat response？

**Comment by andrewgodwin** [comment]
You'll need to handle that yourself using a timer or similar; the only mechanisms we ship with Channels are the two above. Is there a reason you want to disconnect them? Idle connections don't take up much resources at all.

You could also do the timeout on the client end which would be much easier for you.

**Comment by lingliqianxun** [comment]
Because I am afraid a malicious client could connect to the server.OK,thank you very munch.=^_^=

**Comment by thaxy** [comment]
Maybe worth to point out that daphne sends by default every 20s a ping and expects the client to answer back within 30s.
