### ISSUE TITLE
Javascript client is susceptible to "thundering herd" reconnect issues at scale

### ISSUE THREAD

**Issue by dougkeen** [django/channels#568]
I noticed the new javascript client uses [ReconnectingWebSocket](https://github.com/pladaria/reconnecting-websocket) as its core socket implementation. The exponential backoff algorithm in that library doesn't include any sort of jitter, so reconnect attempts across many clients will still be clustered after a large-scale disconnect event. [This blog post](https://www.awsarchitectureblog.com/2015/03/backoff.html) illustrates the problem well.

With apologies for any apparent self-promotion, the [PersistentWebsocket](https://github.com/phound-inc/persistent-websocket) library provides jittered backoff and some other features I've commonly needed when writing real-time clients (pinging, network/reachability checks, etc), and its API is very similar to ReconnectingWebSocket. I'm also the maintainer and could probably provide quick turnaround for any problems surfaced through use in the channels client.

**Comment by andrewgodwin** [comment]
Pinging @fcurella - how easy would it be to swap this out?

**Comment by fcurella** [comment]
@andrewgodwin seems pretty trivial, since they mostly share the same API.

FWIW, I choose ReconnectingWebSocket because a) the usefulness of the reconnecting behaviour and b) its popularity.

I'd rather fix ReconnectingWebSocket if possible. But I'm looking at its repo's issue and PRs, it's unmaintained since April 2016.

The only concern I have about PersistentWebsocket is that it's (still) pretty unknown - which is understandable for a library that's only 28 days old.

**Comment by dougkeen** [comment]
FWIW, I know everything about that library, because I wrote it ;)

**Comment by germanjoey** [comment]
Hi Doug,

This library looks pretty good to me, and I'd like to use it for my own
channels javascript client (that I've yet to publish) instead of
ReconnectingWebsocket. Could you point out what API differences exist
between PersistentWebsocket and ReconnectingWebsocket (that would prevent a
drop-in-replacement), and if there's anything additional that I'd need to
configure?

Thanks!
Joe

**Comment by dougkeen** [comment]
The primary difference is PersistentWebsocket requires explicit opening of the connection (`socket.open()`) instead of automatically making the connection on object construction (like native `WebSocket` does). ReconnectingWebsocket has an `automaticOpen` option (defaulted to true) to toggle that connection behavior. If there's enough interest, I can implement something similar in PersistentWebsocket.

Otherwise, it's mainly just differences in the `options` object, which are documented on the github homepages of each project.

**Comment by dougkeen** [comment]
Sorry, just noticed I linked to the wrong ReconnectingWebSocket project in the original issue, which I've corrected above. @fcurella turns out that project showed signs of life in late November of last year.

**Comment by dougkeen** [comment]
Upon looking at the _correct_ [ReconnectingWebSocket](https://github.com/pladaria/reconnecting-websocket) project, it does appear that it implements some jitter into the very first reconnection delay (as [RFC6455](https://tools.ietf.org/html/rfc6455#section-7.2.3) suggests), so the problem in the title of this issue actually doesn't apply.
**This issue can probably be closed** 

Personally, I also like having:
- a network/web reachability check available (so clients aren't stuck waiting for `${maxReconnectionDelay}ms` once reconnected to the internet after sleeping or going offline in other ways)
- some sort of pinging to actively detect if the connection is dead

... which are not provided in the ReconnectingWebSocket lib.

**Comment by fcurella** [comment]
@dougkeen I think both of those features would be better added directly to `ReconnectingWebSocket`. Whatever options you give to the `WebSocketBridge` constructor are already passed down to `ReconnectingWebSocket`.

**Comment by dougkeen** [comment]
I'll go ahead and close this ticket.
