### ISSUE TITLE
Idea: Individualize messages per channel in a group

### ISSUE THREAD

**Issue by matclayton** [django/channels#582]
I'm investigating building a GraphQL subscription system on top of Channels, and I think theres a few core building block missing which make it fairly tough to build.

In GraphQL a client can request to be notified of specific event types, and when that even happens the server should respond with the data requested. Crucially the response can vary on a per client basis to the same event, depending on what query is included when the subscription is initiated by the client.

We therefore need a mechanism of allowing multiple clients to listen for the same event, which can be easily achieved with groups, however we need to send back a different response to each one based on the initial query the client sent in. Right now I can't see a good architecture to achieve this in channels.

My proposed solution would be to modify the groups feature, adding a variable to group.add() to store additional information, backed into redis/ipc as required. This data would then need to be used on a per channel basis in the send_group() function (https://github.com/django/asgi_redis/blob/master/asgi_redis/core.py#L332), probably by allowing users to provide a render_message function for their use case, and calling it with the pre-stored data. I've been trying to figure out a cleaner solution using the current building blocks, but can't find anything which makes sense. 

Does anyone have am alternative suggestion? Or would such an update make sense to be included in channels core? We might be able to commit some time to building this out, but I'd like to see if theres any appetite for this first. 

There's likely a bunch of use cases which this could enable, like in game events, where each observing user requires a slightly different update, or chat rooms where the content is rendered differently on a per user basis based on preferences etc.

**Comment by andrewgodwin** [comment]
You're right that this would be a great feature, and I initially looked into ideas like it for the groups functionality that is built-in to Channels, but ultimately what it means is that you have to shell out to a Python function to send to each member in a group, which is difficult in the Redis sharding case (where the plan is to do the group expansion in Lua inside of Redis for efficiency) and impossible in the RabbitMQ case (where you don't know who's on the group exchange from the Python end).

For that reason, I think this is something that could be built as a reusable app on top of Channels - basically replacing the groups functionality we ship with something that provides more features but thus cannot run in as many situations. I don't want to include it in the core implementation because, as I've mentioned above, it adds yet another constraint to the existing set that makes it harder to run across backends (and I am sometimes in two minds that we added groups in at all!)

**Comment by matclayton** [comment]
No worries! Thanks for the quick response, and it all makes sense.

I was also wondering if it was possible to solve this with using Group() as is and fanning out to intermediate channels which do the computations and reply's, stashing the data needed in channel_session on add(). Any thoughts on that as an alternative approach?

**Comment by andrewgodwin** [comment]
Maybe, but Group is a pretty simple thing (a set store with add and remove commands, and a piece of code that loops over it on send) so I'd be tempted to just implement it more directly. If you're trying to build something to send to tens of thousands of users, though, and you want to do computation on each message, then yes, you're going to need some kind of intermediate channel or maybe even a set of fanout processes.
