### ISSUE TITLE
Understanding Consumer Atomicity

### ISSUE THREAD

**Issue by sachinrekhi** [django/channels#584]
I'm in the process of upgrading to Channels 1.1.1 from 0.13.1 since I'm running into an issue where socket messages are occasionally being dropped by the server when using enforce_ordering, which appears to be addressed in 1.1.0.

In doing so, I'm trying to understand the implications of consumer atomicity. I've read the docs, but want to ensure my understanding is correct.

One of the features I currently enjoy about Channels is that I can send a reply message to a client in the middle of a consumer handler and then continue server processing. This enables me to provide a speedy response to the client yet still do some server processing afterwards without having to use any additional queue / delay servers, etc. So to continue to support this use-case, it sounds like whenever I send such replies, I now need to use immediately=True to continue this behavior, correct?

Similarly, I often use Channels to send messages to clients as an alert of activity that another user is doing. This looks like within a classic Django view, I use the Group() capability to send the alert to another client and also continue doing other processing for the current user. I assume Group's send method also has an immediately=True capability that I can use in this case as well? (If so, might be helpful to update the Reference section to show that the send(content) also now supports immediately as an optional param).

Given my understanding, it looks like I'm going to want to set immediately=True in all of my cases to ensure fastest response to the client. Given this, I'm trying to understand the scenario where I don't want to send it immediately? It looks like the only use case is the one mentioned in the docs, which is you are sending something to another channel that will have a consumer handler associated with it so it doesn't start processing before the current consumer finishes. But in the cases where they are just reply channels, then immediately=True makes sense. Did I get this right?

Also, in the case where the send() call is at the very end of my consumer, I assume I am indifferent than between setting immediately=True or not? Or is there some optimization/benefit of not setting immediately=True?

**Comment by andrewgodwin** [comment]
The reason atomicity is there is primarily to enforce good design constraints - since your consumers should be very short-lived (as they don't run asynchronously, they are blocking code while they're running), there should be no real difference between sending at the end and in the middle unless your consumers are taking too long.

You can pass immediately=True to overcome this as you suggest, but unless you're spending all your CPU time inside a consumer hammering something (or waiting for the database), that's actually not what you want. We're not going to change the default, but if you're happy overriding the safety you can go ahead and send immediately.
