### ISSUE TITLE
Test message has no 'method' or 'client' keys

### ISSUE THREAD

**Issue by gyermolenko** [django/channels#601]
Hi.

When I submit message to channel via HttpClient, like so
```client.send_and_consume('websocket.connect', {'value': 'my_value'}, path=url)```

in consumer I get message (channels.message.Message object) without 'method' or 'client' keys (and therefore can't transform it with AsgiRequest(msg) and such).

Could you clarify if it is a bug?

ps 
channels==1.1.2 
asgi_redis==1.2.1

**Comment by andrewgodwin** [comment]
I believe it may be a bug - @proofit404, what do you think?

**Comment by proofit404** [comment]
First of all code above gives me `TypeError` which is obvious because `send_and_consume` has different signature.

I don't think this is a bug. Since Daphne construct message content itself, we force users to copy this internal behavior in tests. Add right `method` and `client` keys to the content dict is good example.

I think we can add helper method like `client.http_send_and_consume` which will provide right content. But I'm against `send_and_consume` modification because it should not be coupled to the HTTP protocol.

**Comment by andrewgodwin** [comment]
Yeah, I've seen a couple of bug reports about this now but it doesn't make sense that it would work like this - last time I recommended to use the plain `Client`. I think the problem is that the testing docs make use of it in this way here: https://github.com/django/channels/blame/master/docs/testing.rst#L160

**Comment by proofit404** [comment]
It's nice to have http helper. If `method` key is required to handle this message (I guess it is so, because it goes into django view machinery), we need provide `method` key. Maybe even make it consumer method keyword argument.

But I'm not so certain about `client` key. It probably required by some http middleware, but is it necessary in general?

**Comment by Krukov** [comment]
I know, that is strange, but the `HttpClient` is for testing webscoket consumers (not http). It seems that this introduces misunderstandings.

**Comment by proofit404** [comment]
Does `HttpClient` useful only for websockets? Maybe we can have both http and ws test clients? Or have one "web" client with send http and send ws methods.

**Comment by gyermolenko** [comment]
> First of all code above gives me TypeError which is obvious because send_and_consume has different signature.
@proofit404 hi. Could you please give me some advice regarding the situation?
How should I approach testing consumers, what is the correct signature for send_and_consume? Should I use this method at all? Should I wait for updates in documentation / next channels release?
Alas, for the moment I'm just confused with your conversation...
Thank you in advance.

**Comment by Krukov** [comment]
`HttpClient` designed for use with websocket, and I have never tested it for http consumers :man_facepalming: . I thought that for testing http developers can use django client  https://docs.djangoproject.com/en/1.11/topics/testing/tools/#the-test-client

@gyermolenko  Why you trying to transform message  to the `AsgiRequest`? 
Looks like you trying to test `websocket` consumer (`client.send_and_consume('websocket.connect', {'value': 'my_value'}, path=url)`), at this way you don't need to  transform to the `AsgiRequest` manually.

**Comment by gyermolenko** [comment]
@Krukov thanks for your reply.
Yes, I am trying to test ws consumer. The thing is - my destination url contains GET parameters which I try to obtain with transformation to AsgiRequest.

**Comment by gyermolenko** [comment]
like [here](https://gist.github.com/leonardoo/9574251b3c7eefccd84fc38905110ce4#file-auth_token-py-L45)

**Comment by proofit404** [comment]
@Krukov I'm sure Django built-in http client will go directly into url router. This way we skip consumer for `http.request`. So errors inside consumer are hidden for this tests.

**Comment by Krukov** [comment]
@gyermolenko  You need to add 'query_string'  to a message, you can do this with `content` kwarg
```python
client.send_and_consume('websocket.connect', content={'query_string': 'token=mytoken'}, path=url)
```
Also you need to fake `method` like in example that you give.

@proofit404 Yes you right, then I support the idea of separation clients for http and websocket.

**Comment by gyermolenko** [comment]
@Krukov thanks
> content={'query_string': 'token=mytoken'}

helped a lot
