### ISSUE TITLE
Visibility into Channel Messages

### ISSUE THREAD

**Issue by sachinrekhi** [django/channels#606]
I just got the following error:

```
ChannelFull
Cannot requeue pending __wait__ channel message back on to already full channel websocket.receive
```

Is there any mechanism by which I can gain visibility into what messages are filling the channel? Curious if there were any ways to easily peer into the channel queue?

While within my consumer I can certainly do my own tracking, that would only tell me the messages being currently processed, not the ones that are filling the queue. So seems like I'd need a hook into daphne or redis itself?

**Comment by proofit404** [comment]
`websocket.receive` channel full basically means your incoming traffic load is more than your infrastructure can process.

You have two options. You can increase number of worker processes or increase this channel capacity. Or you can do both.

**Comment by andrewgodwin** [comment]
You can't see into the channel queue, only receive from it, with the main API. It's possible to look in the Redis lists if you're using that, but there'll never be an official API for it as it would make things harder to optimise.

Having a full `__wait__` channel just means that a message wasn't processed properly and `enforce_ordering` has run out of space to try and queue up ordered messages in. You'll have to work out what's not correctly consuming things to fix it, size changes won't help.

Ideally when this happened we'd signal back to Daphne to drop the WebSocket connection due to errors, I haven't figured out the best framework for doing that generically yet.
