### ISSUE TITLE
ChannelFull Error

### ISSUE THREAD

**Issue by tijazatrook** [django/channels#658]
Hi Andrew, 

Hope you are well. I have been experiencing some ChannelFull errors and wanted to request you for some guidance. I know that you mentioned that the default Channel capacity is a 100 messages/second, could you tell what the constraints are on the size of the message queue. Just wanted to know that whether large messages (even if they are less than a 100/second) could potentially cause ChannelFull errors. 

The application I am working on primarily relies on Django Channels and just has 3-4 RESTful endpoints. As such I have set the channel_capacity as follows:

```javascript
"channel_capacity": {
	"http.request": 100,
	"websocket.send*": 200,
}
```

Since I have drastically increased the websocket capacity, wanted a second opinion on this. Do you see any issues with such a configuration?

Thank you once again for Django Channels! :) 

-Tahir

Follow-up Link: https://github.com/django/channels/issues/329

**Comment by andrewgodwin** [comment]
The capacity is not "100 messages/second", it is "100 messages" - you need to make sure you have workers draining messages out of the channels as fast as they are put in, otherwise you'll always end up with a channel being full.

Your configuration seems OK for large traffic, but you should measure your latency for connections, and if it gets higher, you definitely need to launch more workers. If you'd like to instrument the channel layer, the Redis layer has statistics methods you can call to get the current size (number of messages in) certain channels, and the end-to-end latency.

**Comment by tijazatrook** [comment]
Thank you Andrew! That makes sense.

**Comment by jobelenus** [comment]
Apologies Andrew for commenting on a closed issue. But I was searching the repo today for `channel_capacity` in the repo. And there is zero code that references that name. I also searched in the Daphne project (just in case) and similarly found nothing. I am first wondering if this has been renamed (I see nothing in the official read the docs) or moved? And second I am wondering what all the possible dict entries and defaults *actually are* (e.g. I don't want to change something like `websocket.send` thinking I'm increasing it and actually am decreasing it).

Thanks

**Comment by andrewgodwin** [comment]
You configure it on the channel backend, so you'll find it over in the `asgi_redis` repo - the default is 100, I believe.
