### ISSUE TITLE
Websocket sessions break custom session backends

### ISSUE THREAD

**Issue by koole** [django/channels#668]
When using a custom session backend, django-channels removes extra information saved in the session. For example, we use the django-user-sessions package and once a websocket is opened the user_id, ip_address and user_agent are removed from the session.

I think the fault lies in [this piece of code](https://github.com/django/channels/blob/627b97c317a6c3ceafa1c8f1192633d1c85c93ff/channels/sessions.py#L28) which does not pass the extra parameters as required.

With plain django this works because the session is set in the middleware which is swapped out. But there is no such option for django-channels?

There are several other people running into this issue too: https://github.com/Bouke/django-user-sessions/issues/55

**Comment by andrewgodwin** [comment]
Channels doesn't use sessions like normal Django does; they're tied against a `reply_channel` object, and never even see a hint of a request (unless you use `http_session`, I guess). We don't even have the extra parameters around to set as there's no middleware layer involved with WebSockets, so unless there's a specific code change you know we can do, I'll have to close this.

**Comment by snoepkast** [comment]
Hey,

So I'm new to websockets and I'm a bit confused. The behaviour I'm seeing is that channels creates a new session every time a websocket is opened. Which is basically everytime the browser loads the page. This pollutes the session table with a lot of sessions and means that letting users manage their sessions (like with django_user_sessions) is no longer a good feature to have.

Before I say anything stupid I have a couple of questions (perhaps dumb ones):

1. Why do websockets need sessions? The connection stays open so if you just want to authenticate users that can be once during the setup based on the http session right? 

2. If you need websocket sessions, can't you fetch the same websocket session again when the page is loaded, since it's based on the http session key?

3. If websocket sessions are indeed differently used from http sessions, why do you use the http session backend if that means it's no longer possible to add extra features to a custom backend like with django_user_sessions? Maybe do it in a websocket_session_backend or something?

**Comment by andrewgodwin** [comment]
1. Websocket processing is non-sticky, which means that if you need to store anything between events (e.g. auth information) it must be persisted outside of a process. I am looking into ways around this, but that's the way it currently is (making things sticky makes scaling incredibly hard)

2. Each socket connection looks entirely different from the backend, and it is not based on the HTTP session at all - instead, the sessions are just per "incoming socket".

3. There is a separate setting for the channel session backend if you want, we just default to whatever you have as the main one.

**Comment by snoepkast** [comment]
Ah thanks for explaining, I think answer 3 might be the solution for our case. Setting the `CHANNEL_SESSION_ENGINE` back to the default django one will probably solve our issues.
