### ISSUE TITLE
ChannelLiveServerTestCase doesn't work together with 'mock' because uses separate processes

### ISSUE THREAD

**Issue by oTree-org** [django/channels#707]
I need to do browser testing using Selenium/Splinter, so I used `ChannelLiveServerTestCase`. I want to test that performing certain actions on my page results in the correct API calls being made to boto/AWS on the back-end. So, I mocked the boto client using `unittest.mock`. However, after launching the Selenium test, I could see my mock was never called. I looked a bit more and found that `ChannelLiveServerTestCase` launches a separate process, unlike Django's `LiveServerTestCase`, which just uses a thread in the same process. Because mock patches the object within the process, it seems it wasn't applying to the server process.

Is there a way for me to do browser testing together with mocking? I know I could make the server process also use a mocked boto connection, but then it's 2 separate mocks, so my tests can't track what calls are being made on the server.

Django 1.8.8, channels 1.1.6, daphne 1.3.0; latest versions of all related libraries.

**Comment by proofit404** [comment]
Hi, you're absolutely correct.

Channels live server uses multiprocessing because of twisted internal reactor implementation. It's event loop is global and can't be started second time. So we start new process to separate twisted state for each test run.

In you situation I prefer to run your own stub server in the main process as separate thread. And in the end of each test just assert its state.

Also you can subclass live server itself and inject mocks and asserts in the subprocess. But I think this approach is flaky.

If you need further assistance feel free to ask more questions in the Django users mailing list.

**Comment by oTree-org** [comment]
Thanks! I will try those approaches.
