### ISSUE TITLE
Latency is surprisingly high.

### ISSUE THREAD

**Issue by etherealmachine** [django/channels#715]
Not exactly a bug report, but an observation. Under the best setup I could create, channel latency is surprisingly high - 12+ms just to echo a message locally.

I created a small repository to demonstrate the issue, with some docker files to make it as easy as possible to replicate:
https://github.com/etherealmachine/django_channels_latency_test

- Your OS and runtime environment, and browser if applicable
Linux, Python3.4, Chrome 59+

- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)
asgi-redis==1.4.2
asgiref==1.1.2
channels==1.1.6
daphne==1.3.0
Django==1.11.4
redis==2.10.5
Twisted==17.5.0
txaio==2.8.1
txredisapi==1.4.4

- What you expected to happen vs. what actually happened
Expected: Latency of 1-2ms at most.
Actually: 10-12ms at best.

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
runserver pull up 4 workers and says
"HTTP/2 support enabled" and "Using native Twisted mode on channel layer"

- Console logs and full tracebacks of any errors
No errors, just surprising behavior.

**Comment by andrewgodwin** [comment]
When you refer to *latency*, what do you mean exactly? End-to-end WebSocket latency? It looks like it from the attached repo.

But yes, this is not super surprising considering the way runserver/daphne works - it basically has a minimum latency floor due to the internal looping. We're going to fix this in the next major release with big rearchitecting, but given there's nothing I can concretely do to solve this issue directly, I'm going to close it.
