### ISSUE TITLE
Can't install on Winwows 10 (python 3.6 x64)

### ISSUE THREAD

**Issue by PacmanLazy** [django/channels#717]
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -Id:\python\include -Id:\python\include /Tcsrc/twisted/test/raiser.c /Fobuild\temp.win-amd64-3.6\Release\src/twisted/test/raiser.obj
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "d:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Garant\\AppData\\Local\\Temp\\pip-build-n8i18ihh\\twisted\\setup.py';f=getattr(tokenize, 'open', open)(__f
ile__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Garant\AppData\Local\Temp\pip-n3_bieez-record\install-record.txt --single-
version-externally-managed --compile" failed with error code 1 in C:\Users\Garant\AppData\Local\Temp\pip-build-n8i18ihh\twisted\

**Comment by andrewgodwin** [comment]
This doesn't appear to be a problem with Channels, but rather with installing Twisted, which unfortunately I don't know enough about to help you with. Since you're on Windows 10, I would encourage you to look into running things under the Windows Subsystem for Linux (WSL) instead, as it uses standard Linux packages and is a lot easier to manage.

**Comment by PacmanLazy** [comment]
I've solved this by downloading from
http://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted required package
pip install Twisted-17.5.0-cp36-cp36m-win_amd64.whl

[image: Встроенное изображение 2]
I haven't checked it yet, but installation was successful.

2017-08-05 16:29 GMT+03:00 Andrew Godwin <notifications@github.com>:
