### ISSUE TITLE
message.user.is_authenticated seems to return value from user object created on websocket.connect consumer

### ISSUE THREAD

**Issue by alexvelickiy** [django/channels#718]
I'm using @channel_session_user_from_http decorator on websocket.connect consumer and @channel_session_user decorator on websocket.receive consumer

When I connect to websocket with authenticated user, then logout using standard Django view and then send message that is processed by websocket.receive consumer, the message.user.is_authenticated line returns True thought I expected to get False. 

Is there a way to get actual user authentication state at this point?

**Comment by andrewgodwin** [comment]
Not directly - Django's logout stuff is designed more for a HTTP request and doesn't play nicely with Channels right now. We're changing the whole user auth system right now though so I'm going to close this as it won't apply any more.

**Comment by codearm-docker** [comment]
I believe this issue is still relevant. I've got an application set up like this:
```
application = ProtocolTypeRouter({
    'websocket': AllowedHostsOriginValidator(
        AuthMiddlewareStack(
            URLRouter(realtime.routing.urlpatterns)
        )
    )
})
```
Basically, the consumer checks that the user is authenticated before allowing to connect, that works perfectly fine. Like this:
```
async def connect(self):
    if self.scope['user'].is_authenticated:
        await self.channel_layer.group_add('realtime', self.channel_name)
        raise AcceptConnection
    raise DenyConnection
```
Note, that I am not using the `login` and `logout` functions provided by channels, but a DRF login endpoint I created myself. It works perfectly fine, I login using a basic HTTP request and when I try to open the websocket connection proceed successfully, if I am not logged in, the connection is closed as expected.

However, the other way around doens't work. If I am already connected and then I logout using a custom DRF endpoint it has no effect on the websocket. I check the user is still logged in everytime I try to send something through the consumer. Like this:
```
async def trigger_send(self, event):
    user = await get_user(self.scope)
    if user.is_authenticated:
        response = await self.view.get(self.patrols_request, self.tasks_request, user)
        await self.send_json(response.data)
    else:
        self.close()
```
But `user` is always the authenticated user and it is not replaced by an `AnonymousUser` when the Django `logout(request)` has been previously called.

I even wrote a test for this, manually deleting all the sessions from the DB and then triggering `trigger_send`. I get a normal response like the user was still valid:
```
# Log the user out
await database_sync_to_async(client.logout)()
sessions = await database_sync_to_async(Session.objects.all)()
await database_sync_to_async(sessions.delete)()

await sync_to_async(call_command)('realtime', '--test')
response = await communicator.receive_json_from()
```

I am missing something or should we consider this a bug, @andrewgodwin ?

**Comment by carltongibson** [comment]
Hi @codearm-docker: Can you put this in a test case, that you expect to pass but isn't? (If so, it really makes it easier to reason about, and potentially fix.) Thanks.
