### ISSUE TITLE
Channel session doesn't get saved sometimes.

### ISSUE THREAD

**Issue by alexvelickiy** [django/channels#724]
Hi, 

I've noticed that channel session accessed by message.channel_session doesn't get saved in rare cases.
As @proofit404 mentioned once, it's due to something with how sessions handle changes and that I should save it explicitly. 

Why does this happen and would message.channel_session.save() fix this issue?
Would same problem appear with message.http_session so should explicitly save it with message.http_session.save() as well?

**Comment by proofit404** [comment]
Hi,

Session automatically handles own key modification and can't see changes in the objects stored in sessions. Let's see by example:

```python
session['foo'] = 'something' # <- This will be saved. We modify session itself.
session['bar'].append(1) # <- This won't be saved. We modify list stored in the session. The session itself doesn't change.
```
Since `http_session` belongs to HTTP request (the one used to start websocket negotiation) and `channel_session` belongs to the reply channel, they are two separate sessions. So you need to call `save` twice.

Regards, Artem.

**Comment by alexvelickiy** [comment]
Thank you, Artem

In my case assignment
`message.channel_session['foo'] = 'some text' `
didn't work few times.

Yes, I understand that they are different. I'm thinking of replacing channel sessions with http ones. The thing I was asking is if it's possible that same issue may appear with http sessions as with channel session?

**Comment by proofit404** [comment]
Actually `http_session` is available only for `websocket.connect` consumer. It's the only place we have both HTTP request and reply channel. You need to save everything you need in the `channel_session` from `http_session`. Otherwise, this information will be unavailable in the `websocket.message` consumer.

Can you provide example project so we can try to reproduce it and see if we are able to fix it in channels.
