### ISSUE TITLE
Weired behavior with websocket.connect and http.request 

### ISSUE THREAD

**Issue by adminq80** [django/channels#784]
Hi guys, thanks for this project. 

I added the following packages to an existing django project.
```
daphne==1.3.0
asgi_redis==1.4.3
asgiref==1.1.1
channels==1.1.8
```
I also added `channels` to `INSTALLED_APPS`, added `CHANNELS_LAYERS` to settings, created an empty `routing.py` and executed `get_channel_layer` in manage.py. Then, I ran `manage.py runserver` command and I was not able to access any html page. The project stopped working out of the sudden and once I added the following to `routing.py` 

```
from channels.routing import route
from channels.auth import channel_session_user, channel_session_user_from_http
@channel_session_user_from_http
def hello_world(message):
    message.reply_channel.send({"accept": True, 'status': 200})
    message.reply_channel.send({
        "text": 'Hello world',
    })

channel_routing = [
    route('websocket.connect', hello_world),
]
```
The project started working again and I was able to access my old urls. I don't know if this is a bug or not.

**Comment by andrewgodwin** [comment]
You can't have an empty routing file, which is why it broke. I would leave this open so we could have a better error, but the routing system has already been entirely rewritten for an upcoming release and I don't have the spare time to do non-critical fixes to the current release, so I'm afraid I have to close this.
