### ISSUE TITLE
Documentation about how to use groups

### ISSUE THREAD

**Issue by ploggingdev** [django/channels#858]
A few suggestions about how the docs can be improved:

* Add an example about how to send messages to groups in the [docs](https://channels.readthedocs.io/en/latest/one-to-two.html#group-objects) and explicitly mention that "chat" in the example is the name of the group.

* In the channel layers [page](https://channels.readthedocs.io/en/latest/one-to-two.html#group-objects) explain what it means to set a "type" and explain what the types "chat.message" and "chat.system_message" are. What value should I set it to if I want to send a websocket message from a subclass of SyncConsumer? 

* On [this](https://channels.readthedocs.io/en/latest/topics/channel_layers.html#using-outside-of-consumers) page, what is "chat.force_disconnect"?

I'm currently trying to upgrade a project to Channels 2.0 and the biggest pain point is around groups, so thought I'd create an issue to explain the pain points. Thank you.

**Comment by andrewgodwin** [comment]
Agreed on these points - a lot of the docs has some rough edges (and needs full code examples to go along with it)

**Comment by brianmay** [comment]
My understanding is that group messages are sent using `CHANNEL_LAYERS`, meaning each application instance is responsible for sending messages to websockets that it terminates. Have I understood this correctly?

Probably the documentation should mention at least something about websocket clients that join a group and disappear without properly disconnecting. Is this something we need to worry about? Looking at the ASGI spec seems to suggest that ASGI will take care of this for us.

> If a channel layer implements the groups extension, it must persist group membership until at least the time when the member channel has a message expire due to non-consumption, after which it may drop membership at any time. If a channel subsequently has a successful delivery, the channel layer must then not drop group membership until another message expires on that channel.
>
> Channel layers must also drop group membership after a configurable long timeout after the most recent group_add call for that membership, the default being 86,400 seconds (one day). The value of this timeout is exposed as the group_expiry property on the channel layer.

**Comment by andrewgodwin** [comment]
That is a correct understanding, yes (and different from Channels 1, where the application instance did not get to relay messages to the socket, they just went straight there).

Disappearance without disconnection currently means that the messages get sent into a void and expired, the only problem it causes is slowdown. Proper handling of this should be discussed too (like adding `group_discard` calls in the disconnect handler)

**Comment by ploggingdev** [comment]
One question : how do I send a message to a group?

I tried the following, but I get an error message saying that there's no handler for "websocket.send"

```
AsyncToSync(self.channel_layer.group_send)(
    "chat",
    {
        "type": "websocket.send",
        "text": "test",
     },
)
```

Here's the [traceback](https://dpaste.de/quZo)

**Comment by andrewgodwin** [comment]
When you send messages to groups they go to the consumers listening to the group, not to the socket. Try using a `type` of `group.message` and then defining a `group_message(self, message)` handler on the consumer, and it'll pick it up. From there you can do `self.send(...)` inside the consumer.

**Comment by brianmay** [comment]
I think I am gradually understanding this new Channels 2 model.

It looks like the code to send a group WebSocket message hasn't been supplied (yet), we need to do this as explained in the previous message when the consumer for each WebSocket receives the group message. This, in turn, allows us to defined different message types for a consumer, and have different handlers for each type.

Checking my understanding: Ideally, when the user closes the webpage, it will close the WebSocket, which in turn should disconnect the consumer, which in turn should unsubscribe the group.

What happens if the user's network connection goes down without properly closing the WebSocket? Is there any logic to expire/disconnect the consumer? Or is this something we need to do ourselves?

**Comment by andrewgodwin** [comment]
Group membership expires after the `group_expiry` set in the channel layer (it's a day by default), but even if the websocket is closed because the client goes into a tunnel, the `websocket.disconnect` event will still fire on the server side - the only case it doesn't is when the process hard-crashes or there's power loss, which is why it's set to a day.

I'm going to work on a proper chat example over the next week or so that should make this all a lot more clear by supplying a working code example.

**Comment by ploggingdev** [comment]
Thanks for the response.

> From there you can do self.send(...) inside the consumer.

What goes inside `self.send(...)``` if I want to send the message to all members connected to the group?

**Comment by andrewgodwin** [comment]
What I mean is this:

* You send a message to a whole group with a type (say, `chat.message`). This gets sent to the application instance of everyone connected and in the group.
* Each instance receives the message and invokes the matching method (in this case, `chat_message`)
* In that method, you call `self.send({"type":"websocket.send", ...}` to send the data down to the single client that instance is for

This allows you to reformat the message content sent down to the socket differently per client (maybe admins can see more fields, or something)

**Comment by acdha** [comment]
I was just learning this earlier today and if you're working on an update, I think it would have been useful to disambiguate what send means in the channel layer context versus the normal consumer cycle. At first, I assumed it had the same semantics as the websocket interfaces because the example messages used the same format so it was confusing when the normal dispatching didn't occur, `AsyncJsonWebsocketConsumer` didn't decode the `"text"` value in the message I sent, etc. — and then it became much easier after learning that the message could have arbitrary fields without needing to JSON encode them first, that they'd go to the handler methods without first passing through the receive method, etc.

**Comment by andrewgodwin** [comment]
Yup. This will all be made much clearer by actual code examples, I promise!

**Comment by andrewgodwin** [comment]
OK, the channels-examples repo has been updated with a Channels 2 example with groups: https://github.com/andrewgodwin/channels-examples/tree/master/multichat

**Comment by TheoElia** [comment]
is there not a way to send multiple messages at once using the group.send()??

**Comment by andrewgodwin** [comment]
Nope, it's one at a time.

**Comment by TheoElia** [comment]
alright, thanks.

**Comment by datasleek** [comment]
Considering django-channels == 1.1.8. Suppose we have added different reply_channels in a Group. How can we keep track whether message has been successfully received by all the members added in a Group? e.g Suppose we have Group named "chat" and to this Group three reply channels i.e reply_channel1, reply_channel2 and reply_channel3 are added. Suppose sockets of reply_channel1 and reply_channel2 are open but socket of reply_channel3 is in error state. If we execute `Group("chat").send({"text":json.dumps({"welcome":"How are you"})})` then message will successfully be received by listeners at reply_channel1 and reply_channel2 but listener at reply_channel3 will not receive this message. How can i put this message in queue and send to listener at reply_channel3 as soon as socket of reply_channel3 gets opened
