### ISSUE TITLE
Should I migrate to Channels 2?

### ISSUE THREAD

**Issue by AgCouper** [django/channels#879]
Hello,
Even though I've read the the docs about Channels 2, it is still not clear for me what are the advantages of migrating my project to Channels 2. There are a lot of changes under the hood, yes, but what are the benefits of these changes for us, developers? Better performance? Better reliability? Something else? Right now, from my point of view, the prospect of migrating to Channels 2 looks like a lot of work for no reasons, so I can't justify it. 
Could you please explain why should I care about Channels 2 at this point of time (may be I really shouldn't, may be all the great things will come later)?

**Comment by tsiaGeorge** [comment]
I mentioned this here #860. 
But the actual issue is in the protocol server(Daphne) and is pending. 
django/daphne#152

**Comment by andrewgodwin** [comment]
In short:

* Everything runs in a single process, so there's less pieces to deploy (no need for separate `runworker`) and better latency for responses

* It lets you write asynchronous handling much more easily - for example, you can just use `AsyncWebsocketConsumer` and just `await asyncio.sleep(5)` to delay responses rather than having to use the old delay server.

* There will only be limited support for Channels 1 (security and dataloss bugs) going forward

I can't say you need to change - if everything is working as you want it to in 1, then there's no pressing reason to move over. But it's a better solution for most people.
