### ISSUE TITLE
Rate limiting application [Feature Request]

### ISSUE THREAD

**Issue by hishnash** [django/channels#906]
Detailed description of the overall behaviour
---------------------------------------------
Be able to rate limit an upstream (and maybe downstream) messages as part of the ASGI application stack. 

it would be good to include 2 core options that can be extended by the user as and when needed similar to [DRF](http://www.django-rest-framework.org/api-guide/throttling/#api-reference) with an `AnonRateThrottle` and a `UserRateThrottle`.

We should provide an option so that requests wait `asyncio.sleep(n)` if being throttled.

Reasoning why it should be in Channels rather than a third-party app
----------------

This could be in a dedicated package that adds extra ASGI applications for channels for sure, but since most production endpoints these days will want some rate limiting adding it directly into the channels package would be a big plus. Since this would be limited the messages being sent it is different from the rate limiting that is in DRF that is only for HTTP (v1.1) requests.

Examples of usage, if possible (it's easier to discuss concrete code examples)
----------

```python
application = URLRouter(
  [
  url("^/admin/$", AdminPostsConsumer),
  url(
    "^/public/$",
    AnonRateThrottle(
      'websocket.connect',
      burst='5/min',
      sustained='100/day',
      application=AnonRateThrottle(
        'websocket.receive',
        burst='60/min',
        sustained='1000/day',
        application=PublicPostsConsumer
        )
      )
    )
  ]
)
```

or as an `@decorator`

```python
@anonRateThrottle('websocket.receive', burst='60/min', sustained='1000/day')
class PublicPostsConsumer(WebsocketConsumer):
  pass
```

**Comment by andrewgodwin** [comment]
I'm afraid I'm going to have to say "no" - rate limiting is a large field and there's lot of different approaches as to how you throttle and count requests, and where you persist and coordinate client data, and that in my opinion makes it unsuitable for putting into Channels itself (plus the fact that every piece of code we add increases our maintenance overhead on our small team).

As far as I can tell, there's nothing in Channels that would prevent this from being written as a third-party ASGI middleware, and so that's what I would recommend. If there's hooks missing in Channels that would be needed to make it work, then that's a different conversation.

Thanks for such a detailed request, though.

**Comment by hishnash** [comment]
your right I think this could 100% be in a third-party ASGI middleware, I will do it this way, living inspiration from how DRF  persist/coordinate the data :)

**Comment by abersheeran** [comment]
Maybe you can try https://github.com/abersheeran/asgi-ratelimit
