### ISSUE TITLE
JS websocket wrapper expects 'text' argument to be JSON parsed as string

### ISSUE THREAD

**Issue by pedrorojasg** [django/channels#921]
Thank you a lot for your work building Django Channels, it is an amazing library.

Issue: JS websocket wrapper expects 'text' argument to be a JSON parsed as string. (line 310 of websocketbridge.js) and in the 'Consumers' section of the docs it says could be any text, the docs even has an example of text = "Hello world!"

      this.socket.onmessage = function (event) {
        var msg = JSON.parse(event.data);

Copied from: https://github.com/django/asgiref/blob/master/specs/www.rst
Send
Sends a data frame to the client.

Keys:

type: websocket.send
bytes: Byte string of binary frame content, or None.
text: Unicode string of text frame content, or None.
Exactly one of bytes or text must be non-None.

*Solution proposal:* just edit the docs :smiley: 

- OS: Ubuntu 16.04 
- Browser: Google Chrome
Django y Channels 2.0.2
I'm using runserver and Redis as broker.

**Comment by andrewgodwin** [comment]
Well, the docs are written from the point of view of you using WebSockets generically, rather than via our websocket wrapper (which should be used with the `JsonWebsocketConsumer`). I'm probably going to move the JS bindings out into a separate package this week anyway as we can't maintain it, so I don't think it's worth fixing the docs for this one. Sorry.
