### ISSUE TITLE
'AsgiRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by muchwakande** [django/channels#981]
After Installing channels 2.0, am getting this error when I visit the django admin site

**Comment by andrewgodwin** [comment]
Please include all the things the "new issue" template asks for - full tracebacks, versions of all your packages, etc. - or I can't help you. Also specifically your `MIDDLEWARE` setting would be good here too.

**Comment by muchwakande** [comment]
Thanks sirs. The problem was my middleware settings. I hadn't realized that MIDDLEWARE_CLASSES  was deprecated.

**Comment by mohammadtetouan** [comment]
hi 
i have the same err 
but i'm new to programming 
so if you can demonstrate the way you fix the broblem

**Comment by jayankarthik** [comment]
@mohammadtetouan  I had the same issue and I changed MIDDLEWARE_CLASSES to MIDDLEWARE in settings.py as suggested by @muchwakande. That did the trick

**Comment by kasaiee** [comment]
I have MIDDLEWARE in my settings.py but this error exist in my project.
any idea?

```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

**Comment by sadaf2605** [comment]
I have MIDDLEWARE at my settings.py yet I am getting the same error

**Comment by shekoff** [comment]
> I have MIDDLEWARE at my settings.py yet I am getting the same error

Me too

**Comment by aimestereo** [comment]
@andrewgodwin Simple way to reproduce is to use any django middleware that access request.user, here's my setup of [django-structlog](https://github.com/jrobichaud/django-structlog):

1. `pip install django-structlog`
2. Add middleware
```
MIDDLEWARE = [
    ...

    'django_structlog.middlewares.RequestMiddleware',
]
```
P.S. you don't need to configure anything else

**Comment by dc740** [comment]
For anyone running into this for several reasons (ie: using the request.user for django debug toolbar), please make sure the middleware that uses the request.user attribute is run AFTER the middleware in charge of the authentication (knox, or whatever you use), otherwise there won't be any user at all, and you will hit this.

Sorry to post this here, but it's the first result in google. It's easy to fix because it's not a bug in channels, and it could take some time to debug if you are not pointed in the right direction. I thought it could add value and save time to other devs.

**Comment by defnngj** [comment]
Upstairs is right！！

```py
email = request.headers.get('x-account-email')
```
replace with：

```py
email = request.user
```
